### ISSUE TITLE
About the " PgBouncer stats/AWS cloudWatch overview/System stats" panel configuration

### ISSUE THREAD

**Issue by hp521yu** [cybertec-postgresql/pgwatch2#108]
Hello！
Because the online system environment needs to be stable, the version of Centos used is lower, and the manual deployment of PGwatch2 is used.
`"DB overview/Table details/Global DB overview DB overview Unprivileged/Developer mode" Normal data`
![image](https://user-images.githubusercontent.com/36100597/45006815-5754eb00-b02d-11e8-94ee-a79c3aca975a.png)

`“PgBouncer stats/AWS cloudWatch overview/System stats/Replication/Top Sprocs ” No data`

The following templates were successfully imported, but all have no data.
![image](https://user-images.githubusercontent.com/36100597/45006412-6044bd00-b02b-11e8-856f-8728fbab9837.png)
![image](https://user-images.githubusercontent.com/36100597/45006644-a1899c80-b02c-11e8-9b6d-244358042aa5.png)

Prompt no data source
What options do I need to configure?
Still need to add other data sources?
Are there any configuration documents for these monitoring templates?

Sincerely thank you for your help!

**Comment by kmoppel** [comment]
Hi! 1st I would suggest to re-read the section on setting up databases for monitoring [here](https://github.com/cybertec-postgresql/pgwatch2#steps-to-configure-your-database-for-monitoring). 
But in general it's so that half of the dashboards are not meant to work out of the box - depending on the dash needed are extensions "pg_stat_statement" (should be anyways installed for almost all Postgres databases), "pgstattuple", "plpythonu" + the wrapper functions for CPU load on "Overview" and for all panels on the "System Stats". AWS and PgBouncer require additionally some more steps - accordingly settinging up a Grafana datasource with AWS credentials and setting up PgBouncer, so that not the DB itself is monitored but the pool.

**Comment by hp521yu** [comment]
Hi! First of all, thank you very much for your help, I am completely following the steps suggested in the documentation.
About "pg_stat_statement" All my databases are open. This is for sure.
About "pgstattuple", "plpythonu" has also been installed successfully.
As for "the wrapper functions for CPU load on "Overview" and for all panels on the "System Stats"". It should also be set up, but Installing without Docker, I did not find other specific related documents, so it is not sure whether other settings are missing.
At the moment, I definitely want to see the data of the "System stats" template, so see if there are other suggestions. Thank you very much for your help!

**Comment by hp521yu** [comment]
Hi!
Swear to God, my steps are exactly the same as what you wrote, but the situation on the template is like the photo I sent, "No data points".
There is no other way, I can only prepare to uninstall all the software, try again.

**Comment by kmoppel** [comment]
@hp521yu No need to swear :D But hmm...then there should be some errors in the pgwatch2 log or InfluxDB log at least...could you look at those? Possible also from Web UI righthand corner...

**Comment by hp521yu** [comment]
I am very sorry, I just saw your reply to my message, but I have uninstalled the server. The current log can no longer be viewed. I am planning to redeploy it again on the weekend. If there is such an error, I will check the log carefully.
Thank you for your help!

**Comment by kmoppel** [comment]
Closing as no feedback on errors anymore
