### ISSUE TITLE
Most INSERT-s (aggregate over selected time period) 

### ISSUE THREAD

**Issue by gvsrini** [cybertec-postgresql/pgwatch2#154]
Your tool is simply mind-blowing. Hats off for sharing it in the community.

Here's my current issue:

I am comparing my latest docker (today's version) install with what's on your demo portal:

https://demo.pgwatch.com/d/30fdbcb60/tables-top?orgId=1

![image](https://user-images.githubusercontent.com/150018/55853631-93ca6580-5b7f-11e9-8a14-1ce80e4ef4a4.png)

Your panel is perfect: _Most INSERT-s (aggregate over selected time period)_ This is exactly what I want.

But unfortunately, mine is as below:

![image](https://user-images.githubusercontent.com/150018/55853714-f15eb200-5b7f-11e9-935e-3bd696f584da.png)

This looks plain wrong. I have not inserted 1.3 Bil records in last 15 minutes as shown in this panel, though the total number of rows inserted over the life of table may be right. I just want 
_Most INSERT-s (aggregate over selected time period)_

What do I need to upgrade it to the version that's running on your demo portal.

Pls help.

**Comment by kmoppel** [comment]
Thanks a lot for the feedback! Glad you find it useful :) 
I've corrected the Dashboard now (though I did it already once)...I'm mostly using the Postgres version now and the Demo runs on that also so that's where the difference came from.
So just reload the [dash](https://github.com/cybertec-postgresql/pgwatch2/blob/master/grafana_dashboards/v5/tables-top/dashboard.json) :)
