### ISSUE TITLE
Questions/clarifications on pgwatch2 dashboard

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#195]
Hi Kaarel and Team,
 Thank you and your team for helping me with pgwatch2 installations.
 I am excited to see the various dashboards and stats for my database now - and you guys have integrated all so nicely.
I have a few questions/clarifications on some items on the Stat_statements overview and DB overview dashboards.
I would appreciate if you can clarify or provide some documentations related with my following questions:
 
Dashboard:Stat-statements 
==================
Q 1. What is the use/meaning of the min. "pg_stat_statements.calls" ? Its list allows to select  
        1,10,100,1000,10000 --  Are we displaying statements that were called/executed a minimum 
        number of 1,10,100,1000,10000  times within the selected time period?
Q 2.  All the metrics of the statements show the queryid. But, how can we view the full 
         statements in the dashboard corresponding to these queryids?
Q 3.  All the metrices (Avg query runtime by queryid, Cumulative 1h query runtime by queryid, 
        and calls per 1h by queryid) show exactly 33 queryids for last 3 hours -  does it mean these 
       33 statements were being run all through last 3 hours? 
Dashboard:DB overview 
===============
Q 1.  All the items (shown below)  that are shown in the top panel - are these average value over 
       the selected time period (for e.g - Last 2 days etc)?
        TPS
        QPS
        Query runtime
        DB size ch 1h 
        CPU Load
Q 2. What is the significance of the Approx Bloat? Why it shows different value in the Health Check dashboard than in the DB overview for the same time period (Last two days)? In the Health-check dashboard we see 145.6 MiB, whereas, in the DB Overview we see a value 72.8 MiB.  

Thanks and regards,
Bikram

**Comment by kmoppel** [comment]
Q 1. Almost correct. Not within the selected time period but global call count. This lets you to only look at regular i.e. application generated queries and leave out some ad-hoc queries.
Q2. When using the wrapper or having privileged access to pg_stat_statements then the query texts are also stored and visible. Like visible on the demo site: https://demo.pgwatch.com/d/86a4c9c9e/stat-statements-top?orgId=1
Q3. Yes for a specific time only queries that had some executions are shown
Q4. Some top panel stuff are based on last 6h data, the tooltip explains it also. If in doubt always click "edit" to see the metric query that should explain everything
Q5. Approx Bloat shows how much extra disk space is wasted. Big numbers can hint at possible problems there. And different values are most probably due to the same 6h override window. You can / should change it if it doesn't make sense to you. This is the way pgwatch2 is meant to be used - it's meant to be customized to your taste.

**Comment by bikramma** [comment]
Thank you so much Kaarel for helping with your explanations.

Thanks and regards,
Bikram Majumdar
Sr Software Developer/DBA, Aqsacom Inc.
c. 1.972.365.3737

[cid:image002.png@01D57232.3F117E60]<http://www.aqsacom.com/>

Disclaimer. This electronic mail message contains CONFIDENTIAL information which is (a) CUSTOMER / SUPPLIER / PARTNER PRIVILEGED COMMUNICATION, WORK PRODUCT, PROPRIETARY IN NATURE, OR OTHERWISE PROTECTED BY LAW FROM DISCLOSURE, and (b) intended only for the use of the Addressee(s) named herein. If you are not an Addressee, or the person responsible for delivering this to an Addressee, you are hereby notified that reading, copying, or distributing this message is prohibited. If you have received this electronic mail message in error, please reply to the sender and take the steps necessary to delete the message completely from your computer system. Statement and opinions expressed in this e-mail are those of the sender, and do not necessarily reflect those of AQSACOM. AQSACOM accepts no liability for any damage caused by any virus/worms transmitted by this email.
