### ISSUE TITLE
On backup and recovery of pgwatch monitoring database and influx database

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#230]
Hi Kaarel -  Thanks for your quick response related with my question/clarifications on backups and recovery of pgwatch database -- issue# 229. In your response, you noted that you have updated your instructions for the restore process for the latest Influx versions. How do I get these latest instructions?
And, as I requested earlier, I wanted to understand step 3 that is needed for upgrading the container:
docker run ... -v ~/pgwatch2_backups:/pgwatch2_backups:rw,z …

Would you be able to clarify clearly the various arguments/parameters that are needed for the above command?

Also, can you please provide me any good links/examples on how to run a cron job to take the pgwatch backups from within the pgwatch container.

Thanks and regards,
Bikram

**Comment by kmoppel** [comment]
Hi, updated Influx restore instructions commit was also linked to the issue, this one: https://github.com/cybertec-postgresql/pgwatch2/commit/24ac1516c76c62188b92a6d8f683614b29e40304
About the volume command - the "z" option tells Docker that two containers share the volume content, i.e. the old and the new one at the same time even.
Hard to give a Cron sample - requirements are always very different there, the simplest way I guess would be to alter the existing take_backup.sh script a little so that in the end you push generated SQL dumps and Influx backup folder to some other server via rsync for example.
