### ISSUE TITLE
Installation of pgwatch2 non-docker - need more clarification to your response on #248 

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#252]
Hi Kaarel,

Thanks for your time and quick responses to my questions/clarifications -- really appreciate very much.
I need a little more clarification on your response to the following question:
<<Q 2. Why do we need the InfluxDB installation -- is it mandatory for pgwatch2 non-docker individual installation?>>
You said:
Q2: No, it's not mandatory. Only when you want to store your metrics in InfluxDB

Questions/Clarifications:
 Q1. Where/which step of installation will allow us to specify that we want to store the metrices in the pgwatch2 database itself instead of storing/requiring the influx db?
 Q2. Without the timeseries features provided by influx db, how do we get all the similar timeseries functionalities by using only the pgwatch2 postgres?

Thanks and regards,
Bikram

**Comment by kmoppel** [comment]
Q1. Where/which step of installation will allow us to specify that we want to store the metrices in the pgwatch2 database itself instead of storing/requiring the influx db?
A1:  There's no installer step as such. one just needs to prepare the metrics store separately and point the pgwatch2 to that store. Needed parameters depend on the selected metrics store so the "datastore" is the most important. Postgres relevant params are described in the readme [here](https://github.com/cybertec-postgresql/pgwatch2#to-use-an-existing-postgres-db-for-storing-metrics) and Influx ones in the "Install Go and compile the gatherer" chapter.
Also I would not recommend to put the config and metrics in the same DB but in a separate one on the same instance.

Q2. Without the timeseries features provided by influx db, how do we get all the similar timeseries functionalities by using only the pgwatch2 postgres?
A2: Postgres has actually all the functionalities of InfluxDB and standard SQL provides even more query possibilities, it's just a matter of what volumes of data are gathered. InfluxDB is much more IO efficient with dozens of monitored DBs.

**Comment by bikramma** [comment]
Hi Kaarel,
Thank you so much for your time and response. Really appreciated all your help and patience with me. 
If you can allow me to clear me further:
In A1, you said  ' Needed parameters depend on the selected metrics store so the "datastore" is the most important.'.   By "datastore"  I am assuming  you are referring to the Add data source configuration  in Grafana UI  which creates a corresponding data source record in the data_source table of pgwatch2_grafana database --- right?  
As per the documentation in step 2.2, we have two options to create our metrics data source:
  1. We can add our data source(s) via the Grafana UI  
      or,
  2. We can adjust and execute the "pgwatch2/bootstrap/grafana_datasource.sql" 
Q 1.
I see that we are using influxdb as the  data source in the  pgwatch2/bootstrap/grafana_datasource.sql.  And, it specifies 'root','root'  for the password,"user" as shown below.  I am assuming we need to adjust/change the root(host root account) password here -- right?
Script: pgwatch2/bootstrap/grafana_datasource.sql
---------------------------------------------------------
insert into data_source (org_id, version, type, name, access, url,
  password, "user", database, basic_auth, is_default, json_data, created, updated
  ) values (
  1, 0, 'influxdb', 'Influx', 'proxy', 'http://localhost:8086',
  'root', 'root', 'pgwatch2', 'f', 't', '{}', now(), now()
  );
-------------------------------------------------------------
Q 2.
 I also see you have put a script to use PostgreSQL as the metric data store - 
         as shown below:
Script:pgwatch2/bootstrap/grafana_datasource_pg.sql
------------------------------------------------------------
insert into data_source (org_id, version, type, name, access, url,
  password, "user", database, basic_auth, is_default, json_data, created, updated
  ) values (
  1, 0, 'postgres', 'pg-metrics', 'proxy', 'localhost:5432',
  'pgwatch2admin', 'pgwatch2', 'pgwatch2_metrics', 'f', 't', '{"postgresVersion":1000,"sslmode":"disable","timescaledb":false}', now(), now()
  );
--------------------------------------------------------------------
I see we are not using the pgwatch2 configuration database to store metrics but using a separate database 'pgwatch2_metrics' -- is it for performance reasons? 
Q 3.
If we use PostgreSQL/pgwatch2_metrics for our metric data store, do we still get the same monitoring functionalities/timeseries views as we can get using the influxdb?
And, I am assuming we can run the "pgwatch2/bootstrap/set_up_grafana_dashboards_pg.sh" script
to create the dashboards -- right?

Thanks and regards,
Bikram
