### ISSUE TITLE
Very slow stat_statements dashboard using Timescaledb

### ISSUE THREAD

**Issue by henriavelabarbe** [cybertec-postgresql/pgwatch2#280]
Hi,
I just migrated our Pgwatch2 installation to use TimescaleDB.
We were using a dbname_time partitioning before as we monitor a lot of databases (400+).
Our pgwatch2 server is a 16GB RAM/ 4Vcpus VM.
Performance were relatively good but space usage was high : 800GB for a 1 month retention and by tuning the collect frequency.

After creating a new DB with timescaledb, the dashboards using stat_statements are very slow  (more than 15 seconds for stat_statements_top) after just 1 day of ingestion.
From what I see, the TimescaleDB partitioning scheme is based on time and doesn't include dbname.
That means we have just 1 chunk for stat_statements hypertable for 2 days of data by default.
In our database, the current chunk for stat_statements is 9GB after 1 day.

I think most of pgwatch2 dashboard are single db based.
Wouldn't it be beneficial to already partition the metrics hypertable on dbname ?
I'm quite new to TimescaleDB but it seems possible to use at least hash partitioning

Regards,
Henri

**Comment by kmoppel** [comment]
Yes, very possible that the TimescaleDB defaults are not enough for your metric volumes so you need some tuning.
The upcoming pgwatch2 version will also add support for InfluxDB and with below default settings - but you of course need to play around a bit to find some values that work for your hardware / volumes.

```
PERFORM create_hypertable('metric_x', 'time', chunk_time_interval => '2 days');

ALTER TABLE some_metric SET (
  timescaledb.compress,
  timescaledb.compress_segmentby = 'dbname'
);
SELECT add_compress_chunks_policy('some_metric', INTERVAL '1 day');
```

**Comment by kmoppel** [comment]
Closing as added some more info into README (also on Continuous Aggregates that should be very beneficial in this case) and also simplified the TimescaleDB indexing scheme so that it actually seems to performs better now - https://github.com/cybertec-postgresql/pgwatch2/commit/4070327b8feca3f562c0b154458c431b14af7e01 , https://github.com/cybertec-postgresql/pgwatch2/commit/6770a7a03cb326760380399e6e684255a1e3b6a6

Btw, pgwatch2 TimescaleDB partitioning scheme is based on already on dbname, so filtering by dbname should be very fast given data is more or less cached or disks / CPU are fast.
