### ISSUE TITLE
get_load_average

### ISSUE THREAD

**Issue by pmpetit** [cybertec-postgresql/pgwatch2#309]
Hello, i do not understand
the user is superuser, do i have to create helpers function ?

2020-10-12 13:23:09.460 UTC [63368] ERROR:  function get_load_average() does not exist at character 227
2020-10-12 13:23:09.460 UTC [63368] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2020-10-12 13:23:09.460 UTC [63368] STATEMENT:  select
          (extract(epoch from now()) * 1e9)::int8 as epoch_ns,
          round(load_1min::numeric, 2)::float as load_1min,
          round(load_5min::numeric, 2)::float as load_5min,
          round(load_15min::numeric, 2)::float as load_15min
        from
          get_load_average();   -- needs the plpythonu proc from "metric_fetching_helpers" folder

??

**Comment by pmpetit** [comment]
i think helpers are auto-created with auto-discovering dbs...

**Comment by kmoppel** [comment]
Hi, yes getting any non-Postgres information requires still "helpers", even for superusers.
And in YAML mode helpers are created automatically only if you set the "is_superuser" attribute to "true", otherwise you need to roll them out manually or via the [rollout_helper.py](https://github.com/cybertec-postgresql/pgwatch2/blob/master/pgwatch2/metrics/00_helpers/rollout_helper.py) script.

**Comment by kmoppel** [comment]
@pmpetit I cannot replicate this situation with the latest version at least...even when using the "postgres-continuous-discovery" sb type. And user role from the "user" YAML attribute is used also correctly.
