### ISSUE TITLE
v1.8.1 update did not apply for existing application

### ISSUE THREAD

**Issue by Skoffer** [cybertec-postgresql/pgwatch2#312]
v1.8.1 [2020-10-22]

I have tried the update and was not able to see the changes on Grafana side.

- Neither dashboard was tagged.
- Did not find new dashboards.
- DB Overview Session count was not changed to TPS/QPS etc.

I am using volumes.

The upgrade process was:

1. Apply migration script to config store.
2. `docker stop pw2`
3. `docker rm pw2`
4. `docker pull cybertec/pgwatch2:latest`
3. `docker run -d --restart unless-stopped -p 3000:3000 -p 8086:8086 -p 8080:8080 -p 8088:8088 -v pg:/var/lib/postgresql -v influx:/var/lib/influxdb -v grafana:/var/lib/grafana -v pw2:/pgwatch2/persistent-config -e PW2_TESTDB=false -e PW2_IRETENTIONDAYS=90 --name pw2 cybertec/pgwatch2:latest`

**Comment by Skoffer** [comment]
Also FYI after the upgrade my old graphs started to look like a jigsaw https://prnt.sc/v57qpj

**Comment by Skoffer** [comment]
Also FYI

After the upgrade, my old graphs started to look more like jigsaw https://prnt.sc/v57slb

**Comment by kmoppel** [comment]
Hi,

Yes sadly we cannot really update the existing Grafana dashboards in a reliable way...so one needs a fresh Grafana setup or manual import of dashboards definition JSON-s. Some more information here: https://pgwatch2.readthedocs.io/en/latest/upgrading.html?highlight=dashboards#updating-grafana-dashboards

About the "saw" graph pattern - this happens when the collecting interval (in your case 5min) matches or is greater than the aggregation / grouping interval. When both are 5min for example then sometimes it happens that data is collected with a bit of lag so that one aggregation window has 0 events and the other 2. You could try increasing the GROUP BY interval then or decreasing the metric interval.

Closing now as not much to do, but thanks for the report!
