### ISSUE TITLE
Patroni support. Question.

### ISSUE THREAD

**Issue by kearalex** [cybertec-postgresql/pgwatch2#322]
I have a question about monitoring the Patroni cluster. I can not understand why in YAML config file when I setting up the parameter "only_if_master" in "true", daemons on all replica nodes continues to send metrics in Influx?
After reading the documentation in the part of monitoring HA-cluster on the basis of Patroni, I have a view if I assign the following parameters in YAML config file such values:

`unique_name: My_active_app`
`dbtype: patroni`
`only_if_master: true`

And I'll record them on each of the HA-cluster nodes, afterwards daemon pgwatch from only one node will send the metrics to Influx. Specifically, the one where the base is in the Leader state.
But the practice is different. Daemons sends data from all nodes to Influx. 
Is it a bug or a feature?
The value "true" or "false" in the "only_if_master" only affects the tag name with which the metrics of the nodes will be recorded in Influx.
If "only_if_master: true", the tag name will be recorded as "My_active_app".
If "only_if_master: false" then the tag name will be recorded as "My_active_app + server_name_for_node".

**Comment by kearalex** [comment]
Clarification.
On each of the HA-cluster nodes I made a monitoring of database connections. And I saw that daemons don’t send data from all nodes to Influx. In fact, all daemons read metrics only from the database of the active node (leader). It turns out that the active database is loaded with unnecessary requests for metric collection. Well, it’s not logical.
Is it possible to make that only one daemon pgwatch2 works, which is on the active node?

**Comment by kmoppel** [comment]
Hi, based on the description I think you've currently configured things in way that is not intended. If you run the collector on each node you really don't need the patroni mode - just the "only_if_master" flag. When you use separate collectors they're not synced in any way and totally independent, except maybe the "group" attribute that enables "sharding".

Another approach if your want to use the patroni mode would be to define a separate "standby configuration", so that no or only few metrics would be gathered from standbys.
