### ISSUE TITLE
Intermittent "WARN main: sent STOP message" log entries in the gatherer log

### ISSUE THREAD

**Issue by kmoppel** [cybertec-postgresql/pgwatch2#330]
2020/11/30 08:57:41 WARN main: sent STOP message to 2015 gatherers (it might take some minutes for them to stop though)
2020/11/30 08:59:52 WARN main: sent STOP message to 2015 gatherers (it might take some minutes for them to stop though)
2020/11/30 09:01:55 WARN main: sent STOP message to 2015 gatherers (it might take some minutes for them to stop though)
2020/11/30 09:04:00 WARN main: sent STOP message to 2015 gatherers (it might take some minutes for them to stop though)
2020/11/30 09:06:03 WARN main: sent STOP message to 2015 gatherers (it might take some minutes for them to stop though)

**Comment by kmoppel** [comment]
Due to an oversight in v.1.8.1 gathering was internally permanently restarted. Does not cause any real data loss but just inefficient and actually increases the amount of metrics collected a lot - so definitely recommended to upgrade to v1.8.2 as soon as it's out.

**Comment by kmoppel** [comment]
v1.8.2 is now [out](https://github.com/cybertec-postgresql/pgwatch2/releases/tag/v1.8.2) and strongly recommended for all those who installed v1.8.1.

**Comment by ShinIce** [comment]
thank you @kmoppel =)

**Comment by ShinIce** [comment]
hey @kmoppel , I think a follow up here is the best?

I installed yesterday the update to v1.8.2, but still can see those warning:

2020/12/23 10:35:15 WARN main: sent STOP message to 1488 gatherers (it might take some minutes for them to stop though)
2020/12/23 10:37:37 WARN main: sent STOP message to 1488 gatherers (it might take some minutes for them to stop though)
2020/12/23 10:39:40 WARN main: sent STOP message to 1488 gatherers (it might take some minutes for them to stop though)
2020/12/23 10:41:49 WARN main: sent STOP message to 1488 gatherers (it might take some minutes for them to stop though)
2020/12/23 10:43:52 WARN main: sent STOP message to 1488 gatherers (it might take some minutes for them to stop though)
2020/12/23 10:45:55 WARN main: sent STOP message to 1488 gatherers (it might take some minutes for them to stop though)
2020/12/23 10:48:05 WARN main: sent STOP message to 1488 gatherers (it might take some minutes for them to stop though)

since the update until now (~18h) another 650GB where collected 🤔 
If you need more information feel free to poke =)

greetins

**Comment by kmoppel** [comment]
@ShinIce Indeed, seems first fix did not cover replica servers correctly :/ Please try again with v1.8.3. Much thanks for the report!

**Comment by ShinIce** [comment]
@kmoppel thanks for the quick fix =)
pulled and changed, will get back to you later ;) but for now no warning after the restart.

**Comment by ShinIce** [comment]
I would say it is done ;)
no warnings since yesterday and no insane increase of used space.

thanks =)
