### ISSUE TITLE
Some thoughts about backends metrics

### ISSUE THREAD

**Issue by bukem** [cybertec-postgresql/pgwatch2#339]
Hi pgwatch2 team,

I have some questions and thoughts about `backends` metric and want to share with you: we use there CTE `sa_snapshot`, but for two metrics still have to access get_stat_activity() function and for `instance_total` - pg_stat_activity view. I think monitoring should produce as less additional load as possible and from this point, if let's say we have dozens of databases, hundreds of connections and pgwatch2 working in discovery mode the query will be executed regularly for each database. So I think it makes sense to cut the extra work:
1. we can remove `instance_total` from `backends` since we have `numbackends` in `db_stats`, which, in addition, does not require additional aggregation.
2. why do we [filter out](https://github.com/cybertec-postgresql/pgwatch2/blob/master/pgwatch2/sql/config_store/metric_definitions.sql#L13) "autovacuum" activity ? It forces us to run two metrics over `get_stat_activity()` function and at the same time it breaks the concept when the metrics, returned by `backends` group is related to one database. Also, if autovacuum is working with the database, why wouldn't we count it as an active session? In addition, keeping the "per database" concept allows us to show at which bases the autovacuum works more often.

As an example, 9.0 backends query https://github.com/cybertec-postgresql/pgwatch2/blob/master/pgwatch2/sql/config_store/metric_definitions.sql#L12-L33 can be rewritten to

```sql
with sa_snapshot as (
  select * from get_stat_activity()
)
select
  (extract(epoch from now()) * 1e9)::int8 as epoch_ns,
  (select count(*) from sa_snapshot) as total,

  current_setting('max_connections')::int as max_connections,
  (select count(*) from sa_snapshot where current_query != '<IDLE>') as active,
  (select count(*) from sa_snapshot where current_query = '<IDLE>') as idle,
  (select count(*) from sa_snapshot where current_query = '<IDLE> in transaction') as idleintransaction,
  (select count(*) from sa_snapshot where waiting) as waiting,
  (select extract(epoch from max(now() - query_start))::int from sa_snapshot where waiting) as longest_waiting_seconds,
  (select extract(epoch from (now() - backend_start))::int
    from sa_snapshot order by backend_start limit 1) as longest_session_seconds,
  (select extract(epoch from (now() - xact_start))::int
    from sa_snapshot where current_query not like 'autovacuum:%' and xact_start is not null order by xact_start limit 1) as longest_tx_seconds,
  (select extract(epoch from (now() - xact_start))::int
   from sa_snapshot where current_query like 'autovacuum:%' order by xact_start limit 1) as longest_autovacuum_seconds,
  (select extract(epoch from max(now() - query_start))::int
    from sa_snapshot where current_query != '<IDLE>') as longest_query_seconds,
  (select count(*) from sa_snapshot where current_query like 'autovacuum:%') as autovacuum;
```

The changes are only on lines 2, 7, 17, 19 and 22.

BR,
Mike

**Comment by kmoppel** [comment]
Hello @bukem , thanks for your thoughts! You have some valid points. Like that there is currently some slight duplication i.e. some statistics are collected not only one from one metric - this for example is done to keep things simple on the visualization side.

But using the global autovacuum counter indeed seems now a bit counter-intuitive...so probably should change that. The fact that it's filtered in the 'backend' query has just to do with convenience and reducing repetition I think...this could be changed also, but I think it won't make things much more performant.  And there might be even some other cases where in case of having many DBs on one cluster will cause some repetition and one might win a bit with introducing some custom queries...but based on my experience for most users it's not a problem. At least not with the 'backend' query but rather with "table_stats" and "index_stats" if having a lot of tables. Btw, for pure instance level metrics like WAL etc there's alos the "is_instance_level" attribute defined so that the values are cached and re-used withing a 30s window (can be changed).

Will leave the issue open to address the "global" vs "per DB" Autovacuum stats.

**Comment by kmoppel** [comment]
@bukem  I've now improved things a bit based on your suggestions. Thanks!
