### ISSUE TITLE
source database "template1" is being accessed by pgwatch2

### ISSUE THREAD

**Issue by yinan8128** [cybertec-postgresql/pgwatch2#387]
Hello,

1. Once proceed to create database shows that

   Database query failed: source database "template1" is being accessed by other users
   DETAIL:  There is 1 other session using the database.

2. After check, seems pgwatch2 user accessed template1 database caused

   sudo ps aux | grep template1
   postgres  5957  0.0  0.1 2414416 12980 ?       Ss   14:48   0:00 postgres: pgcluster11: pgwatch2 template1 ::1(40668) idle

**Comment by yinan8128** [comment]
Hi,

After pg_terminate_backend function used, then created database successfully

How to prevent pgwatch2 use template1 database please? Thanks

**Comment by markwort** [comment]
dear @yinan8128 ,
the template1 database is always tried first to fetch information about all other available databases, since it should always be present.
https://github.com/cybertec-postgresql/pgwatch2/blob/04d108072e736ffcbaf1179b0591f1979df1f5fd/pgwatch2/pgwatch2.go#L4100

You can avoid this by not using the continuous discovery features and specifying the databases, for which you'd like pgwatch2 to gather metrics, explicitly in the web ui or instances.yaml config file.
