### ISSUE TITLE
Metrics improvements

### ISSUE THREAD

**Issue by ants** [cybertec-postgresql/pgwatch2#45]
Some notes I gathered when setting this up.

In table details:

* For table size it would be good to have toast table size too.
* Scans and probably others use mean() to calculate number of scans. If there are multiple tables with same name in different schemas this is wrong. sum() would be better.
* 1h rate in 1min timeslices leads to confusing numbers. If there is an occasional sequential scan it shows up as a spike of 60 scans per hour. I guess just using 1m rate would be more intuitive.

Stat statements overview
* Legend is mostly useless and should be disabled.

**Comment by kmoppel** [comment]
"Table details" part changed...but "stat statements" legend is indeed non-optimal due to Grafana limitations..currently it's only good for copying the "queryid" and also one should change the filtering conditions manually (e.g. add min call count etc) when there are too many queries shown. Will close the issue though currently as there's a separate one already for that.
