### ISSUE TITLE
"Global overview" dashboard implementation

### ISSUE THREAD

**Issue by patdenis** [cybertec-postgresql/pgwatch2#63]
Hi,
i'am testing pgwatch2, and i see that there is a "DB overview".
i am interested to a dataserver overview, for monitor the general state, and in case "grep" the single db. i must have to duplicate configuration and modify query metrics?
thanks
Denis

**Comment by kmoppel** [comment]
Hi Denis! 
No the metrics should be all there, you just need to get creative with Grafana and create a dashboards that you like :) But yes, maybe indeed a good idea to provide on "Global overview" out-of-the-box. Will leave the ticket open. Thanks for the input!

**Comment by henriavelabarbe** [comment]
Hi,
I'm also interested by such a feature.
I have a draft hierarchical dashboard based on the cluster_name and the db_name.
We have 20+ databases by cluster and I'm also wondering how much overhead the plpython host monitoring is generating (collect and influxdb volume).
I would love to have a cluster aware collect mechanism and dashboards for the metrics that are at cluster level (where 1 query would get information for all databases).

Regards,
Henri

**Comment by kmoppel** [comment]
Hi @henriavelabarbe! Good timing...just added the dashboard:) See here: https://github.com/cybertec-postgresql/pgwatch2/tree/master/grafana_dashboards/v5/global-db-overview

Not sure about that "cluster aware collect mechanism" though...could you elaborate?

**Comment by henriavelabarbe** [comment]
Hi,
That's a very good timing thanks!
I meant to collect pg-stat-statements or pg-stat-activity only once for all dbs in 1 instance.
Thanks for sharing your work! 

Regards, Henri
⁣Envoyé par BlueMail ​

Le 30 mai 2018 à 18:19, à 18:19, Kaarel Moppel <notifications@github.com> a écrit:

**Comment by kmoppel** [comment]
Ah now I get the point...it hasn't been implemented because some other metrics still are not globally accessible (e.g. pg_stat_all_tables) - one really needs to connect with the DB, so it's probably clearer to keep the concept same also for the views which would work globally like pg_stat_statements.
To make the situation a bit easier for users one can use kind of "wildcard" host entry in the Web UI - when you don't specify the DB name, all DBs will be added to monitoring.
