### ISSUE TITLE
Helm: outdated version for networking.k8s.io

### ISSUE THREAD

**Issue by barazbay** [cybertec-postgresql/pgwatch2#725]
cybertec-postgresql/pgwatch2/openshift_k8s/helm-chart-k8s-pg-storage/templates/exporter-ingress.yaml
cybertec-postgresql/pgwatch2/openshift_k8s/helm-chart-k8s-pg-storage/templates/grafana-ingress.yaml
cybertec-postgresql/pgwatch2/openshift_k8s/helm-chart-k8s-pg-storage/templates/web-ingress.yaml

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122
The extensions/v1beta1 and networking.k8s.io/v1beta1 API versions of Ingress is no longer served as of v1.22.

{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1

I tried to install helm charts in newer versions of kubernetes with no success because of the outdated version of ingress

**Comment by pashagolub** [comment]
Thanks for letting know! Would you like to provide a patch for it?

Thanks in advance!

**Comment by mariusrugan** [comment]
I agree the chart is not state of the art or maintainable, 

I've adjusted the templates (Grafana ConfigMaps that are not obeying the desired namespace for example, and many small other issues, PodSecurityPolicy deprecated coming from old Grafana chart etc.) rendered it manually on disk, using `helm template`, and cleaned up the components, one by one, again.
I have it working:

![Screenshot 2024-02-03 at 11 44 24](https://github.com/cybertec-postgresql/pgwatch2/assets/143987/cd3dc66b-dd7c-439d-8ac8-c6dc6d5e1dae)


i'll try to come up with a patch which would include:

- cleanup & cleanup and more cleanup, mapping of all resources needed
- Github actions to build and test the chart
- Github pages hosting for the chart 
- Probably a complete different alternative / layout of the chart

Since it is a little bit more than a patch, would it be something for a conversation with other team members from Cybertec ?

**Comment by pashagolub** [comment]
helm and openshift templates are deprecated. No changes/fixes are accepted anymore. Thanks
